name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "mym1359"
          git config --global user.email "mym1359@gmail.com"

      - name: Create or update daily.txt
        run: |
          echo "Last updated: $(date -u)" > daily.txt

      - name: Commit changes
        run: |
          git add daily.txt
          git commit -m "Daily commit: $(date -u)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD
